# Generated by Django 4.1.3 on 2022-11-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
