# Generated by Django 4.1.3 on 2022-11-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRate',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True)),
                ('duty_preferential', models.CharField(max_length=15)),
                ('duty_full', models.CharField(max_length=15)),
                ('additional_measuring_units', models.CharField(max_length=15)),

            ],
        ),
    ]


#'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'