# Generated by Django 4.1.3 on 2022-11-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findcode', '0002_dutyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('duty_preferential', models.CharField(max_length=15)),
                ('duty_full', models.CharField(max_length=15)),
                ('additional_measuring_units', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='DutyRate',
        ),
    ]
